version: '2'
services:
  nginx:
    build: .
    volumes:
      - ./build:/data
    environment:
      - VIRTUAL_HOST=randomport.io
    networks:
      - default
      - proxy-network

networks:
  proxy-network:
    external: true
